var mystring;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var strNumTuple;
mystring = 'Hello'.slice(0, 3);
myNum = 4;
myBool = false;
myVar = 5;
myVar = true;
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
strNumTuple = ['Hello', 4];
var myVoid = undefined;
var myNull = undefined;
var myUndefined = null;
console.log(myVoid);
